- name: Cargar configuracion mysql
  ansible.builtin.debconf:
    name: "{{ selection.name }}"
    question: "{{ selection.question }}"
    value: "{{ selection.value }}"
    vtype: "{{ selection.vtype }}"
  loop: "{{ mysql_conf_selections }}"
  loop_control:
    loop_var: selection
  ignore_errors: true